#cloud-config

runcmd:
  - sudo curl -fsSL -o /etc/apt/keyrings/salt-archive-keyring-2023.gpg https://repo.saltproject.io/salt/py3/debian/12/amd64/SALT-PROJECT-GPG-PUBKEY-2023.gpg
  - echo "deb [signed-by=/etc/apt/keyrings/salt-archive-keyring-2023.gpg arch=amd64] https://repo.saltproject.io/salt/py3/debian/12/amd64/latest bookworm main" | sudo tee /etc/apt/sources.list.d/salt.list
  - sudo apt update -y
  - sudo apt install salt-master -y
  - sudo systemctl enable --now salt-master

write_files: 
  - path: /etc/salt/master.d/network.conf
    content: |
      # The network interface to bind to
      interface: 192.168.0.50

      # The Request/Reply port
      ret_port: 4506

      # The port minions bind to for commands, aka the publish port
      publish_port: 4505
