#cloud-config

runcmd:
  - sudo curl -fsSL -o /etc/apt/keyrings/salt-archive-keyring-2023.gpg https://repo.saltproject.io/salt/py3/debian/12/amd64/SALT-PROJECT-GPG-PUBKEY-2023.gpg
  - echo "deb [signed-by=/etc/apt/keyrings/salt-archive-keyring-2023.gpg arch=amd64] https://repo.saltproject.io/salt/py3/debian/12/amd64/latest bookworm main" | sudo tee /etc/apt/sources.list.d/salt.list
  - sudo apt update -y
  - sudo apt install salt-minion -y
  - sudo systemctl enable --now salt-minion

write_files: 
  - path: /etc/salt/minion.d/master.conf
    content: |
      # The network interface to bind to
      master: 192.168.0.50
